model:
  hidden_size: 32
  num_layers: 1
  dropout: 0

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 500
  sequence_length: 10
  validation_split: 0.2
  use_progress_bar: true

data:
  features:
    - prey_population
    - predator_population
    - predator_prey_ratio
    - herbivore_count
    - carnivore_count
    - flora_count
    - total_fauna
    - total_entities

    - avg_stress
    - biodiversity_index
    - biome_score
    - ecosystem_stability
    - environmental_pressure

    - temperature
    - humidity
    - precipitation
    - co2_level
    - biomass_density
    - atmospheric_pressure

  targets:
    - prey_population
    - predator_population

    - ecosystem_stability
    - environmental_pressure
    - biodiversity_index

    - co2_level
    - temperature


visualization:
  enabled: true
  show_plots: true
  save_plots: true

paths:
  data_path: "research/data/neurosymbolic/neural"
  model_save_path: "research/models/lstm/biome.pth"
  plots_dir: "research/plots/lstm"