model:
  hidden_size: 256
  num_layers: 2
  dropout: 0.4

training:
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.0002
  num_epochs: 150
  sequence_length: 10
  validation_split: 0.2
  use_progress_bar: true

data:
  features:
    - prey_population
    - predator_population
    - flora_count

    - biodiversity_index
    - ecosystem_stability
    - environmental_pressure

    - temperature
    - humidity
    - precipitation
    - co2_level
    - biomass_density

  targets:
    - prey_population
    - predator_population

    - ecosystem_stability
    - environmental_pressure
    - biodiversity_index

    - co2_level
    - temperature


visualization:
  enabled: true
  show_plots: true
  save_plots: true

paths:
  data_path: "research/data/neurosymbolic/neural"
  model_save_path: "research/models/lstm/biome.pth"
  plots_dir: "research/plots/lstm"