hyperparameters:
  batch_size: 32
  hidden_size: 128
  num_layers: 3
  dropout: 0.5
  learning_rate: 0.0001
  weight_decay: 0.01
  num_epochs: 100

data:
  sequence_length: 10
  validation_split: 0.3
  use_progress_bar: true

  features:
    - prey_population
    - predator_population
    - flora_count
    - predator_prey_ratio
    - delta_prey_population
    - delta_predator_population
    - delta_flora_count
    - co2_level

    - biodiversity_index
    - biomass_density
    - ecosystem_stability
    - biome_score

    - environmental_pressure
    - avg_stress

  targets:
    - prey_population
    - predator_population
    - flora_count


visualization:
  enabled: true
  show_plots: true
  save_plots: true

paths:
  data_path: "research/data/neurosymbolic/neural"
  model_save_path: "research/models/neural/biome.pth"
  plots_dir: "research/plots/lstm"
  inference_model: "biome.pth"