hyperparameters:
  batch_size: 64
  hidden_size: 256
  num_layers: 2
  dropout: 0.4
  learning_rate: 0.0001
  weight_decay: 0.0004
  num_epochs: 200

data:
  sequence_length: 10
  validation_split: 0.2
  use_progress_bar: true

  features:
    - prey_population
    - predator_population
    - flora_count

    - biodiversity_index
    - ecosystem_stability
    - environmental_pressure

    - temperature
    - humidity
    - precipitation
    - co2_level
    - biomass_density

  targets:
    - prey_population
    - predator_population

    - ecosystem_stability
    - environmental_pressure
    - biodiversity_index

    - co2_level
    - temperature


visualization:
  enabled: true
  show_plots: true
  save_plots: true

paths:
  data_path: "research/data/neurosymbolic/neural"
  model_save_path: "research/models/neural/biome.pth"
  plots_dir: "research/plots/lstm"
  inference_model: "biome_256h_2l_04dr_0004wd_64bs_00308vl_with_norm_stats.pth"