biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 60 # width
      - 60 # height
  type: "tundra"
  flora:
    - species: "oak_tree"
      spawns: 4
      avg-lifespan: 6 # En a単os lo pongo
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:

    - species: "bramble"
      avg-lifespan: 5 # En a単os lo pongo
      spawns: 3

    - species: "mushroom"
      avg-lifespan: 5 # En a単os lo pongo
      spawns: 7

  fauna:
    - species: "deer"
      avg-lifespan: 8 # En a単os lo pongo
      spawns: 1
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
