biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 20
      - 20
  type: "desert"

  training_mode: true

  fauna:
    - species: "deer"
      spawns: 1
      avg-lifespan: 1
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - MovementComponent:

