biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 67 # width
      - 61 # height
  type: "tundra"
  flora:
    - species: "oak_tree"
      spawns: 12
      avg-lifespan: 30  # En años lo pongo
      components:
        - GrowthComponent:
        - VitalComponent:
        - PhotosyntheticMetabolismComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 20.0
            cold_resistance: 0.0
            heat_resistance: 0.0

    - species: "mushroom"
      spawns: 15
      avg-lifespan: 5
      components:
        - GrowthComponent:
        - VitalComponent:
        - PhotosyntheticMetabolismComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 8.0

    - species: "bramble"
      spawns: 12
      avg-lifespan: 7
      components:
        - GrowthComponent:
        - VitalComponent:
        - PhotosyntheticMetabolismComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 18.0

  fauna:
    - species: "fox"
      spawns: 12
      avg-lifespan: 12
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 5.0
            cold_resistance: 0.0

    - species: "boar"
      spawns: 11
      avg-lifespan: 16
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 16.0

    - species: "deer"
      spawns: 9
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 19.0


