biome:
  climate-model: "climate_model_v1.1"
  fauna-model: "fauna_model_500k"
  map:
    size:
      - 45
      - 45
  type: "tropical"

  training_mode: true
  flora:
    - species: "oak_tree"
      spawns: 80
      avg-lifespan: 30
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - AutotrophicNutritionComponent:

    - species: "mushroom"
      spawns: 120
      avg-lifespan: 7
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - AutotrophicNutritionCompone:

  fauna:
    - species: "deer"
      spawns: 20
      diet: "herbivore"
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - MovementComponent:
        - HeterotrophicNutritionComponent:

    - species: "panther"
      spawns: 8
      diet: "carnivore"
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - MovementComponent:
        - HeterotrophicNutritionComponent:

