biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 60 # width
      - 60 # height
  type: "savanna"
  flora:
    - species: "oak_tree"
      spawns: 1
      avg-lifespan: 15 # En años lo pongo
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:

    - species: "bramble"
      spawns: 1

    - species: "mushroom"
      spawns: 1

  fauna:
    - species: "deer"
      spawns: 1
