biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 67 # width
      - 61 # height
  type: "tropical"



  fauna:
    - species: "fox"
      spawns: 1
      avg-lifespan: 12
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 5.0
            cold_resistance: 0.0
        - HeterotrophicNutritionComponent:
        - MovementComponent: