biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 60 # width
      - 60 # height
  type: "taiga"
  flora:
    - species: "oak_tree"
      spawns: 150
      components:
        - GrowthComponent:
            growth_rate: 0.3
        - NutritionalValueComponent:
            nutritive_value: 0.4
            nutritional_decay_rate: 0.1

    - species: "bramble"
      spawns: 150
      components:
        - DefenseComponent:
        - NutritionalValueComponent:
            nutritive_value: 0.9
            toxicity: 99

    - species: "mushroom"
      spawns: 100

  fauna:
    - species: "deer"
      spawns: 110
      components:
        - NutritionalValueComponent:
        - GrowthComponent:
        - VitalComponent:
    - species: "boar"
      spawns: 50
      components:
        - NutritionalValueComponent:
    - species: "fox"
      spawns: 40
      components:
        - NutritionalValueComponent:
        - GrowthComponent:
