biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 60 # width
      - 60 # height
  type: "taiga"
  flora:
    - species: "oak_tree"
      spawns: 1
      components:
        - GrowthComponent:
             lifespan:  1 # En años lo pongo

    - species: "bramble"
      spawns: 1

    - species: "mushroom"
      spawns: 1

  fauna:
    - species: "deer"
      spawns: 1
