biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 60 # width
      - 60 # height
  type: "tropical"
  flora:
    - species: "oak_tree"
      spawns: 1
      avg-lifespan: 10  # En años lo pongo
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 20.0
            cold_resistance: 0.0
            heat_resistance: 0.0

    - species: "mushroom"
      spawns: 11
      avg-lifespan: 5
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 8.0

    - species: "bramble"
      spawns: 5
      avg-lifespan: 7
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 18.0

  fauna:
    - species: "fox"
      spawns: 4
      avg-lifespan: 12
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 5.0

    - species: "boar"
      spawns: 5
      avg-lifespan: 16
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 16.0

    - species: "deer"
      spawns: 4
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - AutotrophicNutritionComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 19.0


