biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 60 # width
      - 60 # height
  type: "tropical"
  flora:
    - species: "oak_tree"
      spawns: 11
      avg-lifespan: 2 # En años lo pongo
      components:
        - GrowthComponent:
        - VitalComponent:
        - MetabolicComponent:
        - WeatherAdaptationComponent:
            cold_resistance: 1.0
            optimal_temperature: -8
            heat_resistance: 0.1


