biome:
  map:
    size:
      - 75 # width
      - 75 # height
  type: "tropical"
  flora:
    - type: "oak_tree"
      spawns: 4
      components:
        - GrowthComponent:
            growth_rate: 0.3
        - NutritionalValueComponent:
            nutritive_value: 0.4
            nutritional_decay_rate: 0.1

    - type: "bramble"
      spawns: 5
      components:
        - DefenseComponent:
        - NutritionalValueComponent:
            nutritive_value: 0.9
            toxicity: 99

    - type: "mushroom"
      spawns: 4

  fauna:
    - type: "deer"
      spawns: 4
      components:
        - NutritionalValueComponent:
        - GrowthComponent:
    - type: "boar"
      spawns: 3
      components:
        - NutritionalValueComponent:
        - GrowthComponent:
