simulation:
  datapoints: True
  eras:
    amount: 10
    events-per-era: 20

  data:
    snapshots:
      enabled: True
      period_type: "CUSTOM"
      custom_period: 60
      storage_directory: "simulation_records"
      filename_prefix: "biome_snapshot"
      pretty_print: true
      include_real_timestamp: true
