simulation:
  datapoints: true
  eras:
    amount: 10
    events-per-era: 500

  cleanup:
    remove_dead_entities: false

  population-control:
    smart: true

  data:
    visualization:
      trends: true
      evolution: false
      crossover: false

    snapshots:
      enabled: true
      period_type: "CUSTOM"
      custom_period: 60
      storage_directory: "simulation_records"
      filename_prefix: "biome_snapshot"
      pretty_print: true
      include_real_timestamp: true
