simulation:
  datapoints: false

  eras:
    events-per-era: 5000

  cleanup:
    remove_dead_entities: true

  population-control:
    smart: false

  data:
    visualization:
      smart-trends: false
      evolution: false
      crossover: false

    snapshots:
      enabled: true
      period_type: "CUSTOM"
      custom_period: 2
      storage_directory: "simulation_records"
      filename_prefix: "biome_snapshot"
      pretty_print: true
      include_real_timestamp: true


biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 30
      - 30
  type: "tropical"

  training_mode: true

  fauna:
    - species: "deer"
      spawns: 1
      avg-lifespan: 1
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - MovementComponent:

