simulation:
  datapoints: false

  eras:
    events-per-era: 5000

  cleanup:
    remove_dead_entities: true

  population-control:
    smart: true

  data:
    visualization:
      smart-trends: false
      evolution: false
      crossover: false

    snapshots:
      enabled: true
      period_type: "CUSTOM"
      custom_period: 1
      storage_directory: "simulation_records"
      filename_prefix: "biome_snapshot"
      pretty_print: true
      include_real_timestamp: true


biome:
  climate-model: "climate_model_v1.1"
  fauna-model: "fauna_model_pursuits"
  map:
    size:
      - 35
      - 35
  type: "tropical"

  training_mode: true

  flora:
    - species: "oak_tree"
      spawns: 35
      avg-lifespan: 8
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - AutotrophicNutritionComponent:

    - species: "mushroom"
      spawns: 35
      avg-lifespan: 5
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - AutotrophicNutritionComponent:

    - species: "bramble"
      spawns: 30
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - AutotrophicNutritionComponent:


  fauna:
    - species: "deer"
      spawns: 25
      diet: "herbivore"
      avg-lifespan: 4
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 26.0
        - MovementComponent:
        - HeterotrophicNutritionComponent:

    - species: "panther"
      spawns: 6
      diet: "carnivore"
      avg-lifespan: 3
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - MovementComponent:
        - HeterotrophicNutritionComponent:

