simulation:
  datapoints: false

  eras:
    amount: 10
    events-per-era: 50

  cleanup:
    remove_dead_entities: true

  population-control:
    smart: false

  data:
    visualization:
      smart-trends: false
      evolution: false
      crossover: false

    snapshots:
      enabled: true
      period_type: "CUSTOM"
      custom_period: 4 # cada 5 días realmente
      storage_directory: "simulation_records"
      filename_prefix: "biome_snapshot"
      pretty_print: true
      include_real_timestamp: true

    dataset:
      generate: true

biome:
  climate-model: "climate_model_v1.1"
  fauna-model: "fauna_model_200k_updated_cnn_fov17"
  map:
    size:
      - 60
      - 60
    local_fov:
      size:
        width: 17
        height: 17

  type: "tundra"

  training_mode: true
  fauna_ia: true

  flora:
    - species: "oak_tree"
      spawns: 35
      avg-lifespan: 8
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - AutotrophicNutritionComponent:

    - species: "mushroom"
      spawns: 35
      avg-lifespan: 5
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - AutotrophicNutritionComponent:

    - species: "bramble"
      spawns: 30
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0
        - AutotrophicNutritionComponent:


  fauna:
    - species: "deer"
      spawns: 25
      diet: "herbivore"
      avg-lifespan: 4
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 26.0
        - MovementComponent:
        - HeterotrophicNutritionComponent:

    - species: "panther"
      spawns: 6
      diet: "carnivore"
      avg-lifespan: 3
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 28.0
        - MovementComponent:
        - HeterotrophicNutritionComponent:

