simulation:
  datapoints: false

  eras:
    events-per-era: 5000

  cleanup:
    remove_dead_entities: true

  population-control:
    smart: false

  data:
    visualization:
      smart-trends: false
      evolution: false
      crossover: false

    snapshots:
      enabled: true

biome:
  climate-model: "climate_model_v1.1"
  map:
    size:
      - 20
      - 20
  type: "tropical"

  training_mode: true

  flora:
    - species: "oak_tree"
      spawns: 5
      avg-lifespan: 15

    - species: "bramble"
      spawns: 4
      avg-lifespan: 6

  fauna:
    - species: "deer"
      spawns: 3
      avg-lifespan: 6
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 10.0

    - species: "boar"
      spawns: 5
      avg-lifespan: 18
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 16.0

    - species: "fox"
      spawns: 3
      avg-lifespan: 9
      components:
        - GrowthComponent:
        - VitalComponent:
        - WeatherAdaptationComponent:
            optimal_temperature: 19.0

