biome:
  type: "taiga"

  flora:
    - species: "pine_tree"
      spawns: 35
      avg-lifespan: 40

    - species: "arctic_moss"
      spawns: 25
      avg-lifespan: 8

    - species: "spruce_tree"
      spawns: 30
      avg-lifespan: 35

    - species: "winterberry"
      spawns: 20
      avg-lifespan: 10

  fauna:
    - species: "wolf"
      spawns: 4
      diet: "carnivore"
      avg-lifespan: 9

    - species: "moose"
      spawns: 5
      diet: "herbivore"
      avg-lifespan: 10

    - species: "lynx"
      spawns: 3
      diet: "carnivore"
      avg-lifespan: 8

    - species: "snowshoe_hare"
      spawns: 15
      diet: "herbivore"
      avg-lifespan: 4