biome:
  type: "tundra"

  flora:
    - species: "arctic_willow"
      spawns: 14
      avg-lifespan: 7
    - species: "tundra_lichen"
      spawns: 26
      avg-lifespan: 15
    - species: "arctic_cotton_grass"
      spawns: 22
      avg-lifespan: 5
    - species: "saxifrage"
      spawns: 20
      avg-lifespan: 6

  fauna:
    - species: "polar_bear"
      spawns: 3
      diet: "carnivore"
      avg-lifespan: 15
    - species: "arctic_fox"
      spawns: 5
      diet: "carnivore"
      avg-lifespan: 6
    - species: "musk_ox"
      spawns: 15
      diet: "herbivore"
      avg-lifespan: 12
    - species: "arctic_hare"
      spawns: 19
      diet: "herbivore"
      avg-lifespan: 3